// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID   uuid.UUID
	Name string
}

type Todo struct {
	ID          uuid.UUID
	Title       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type TodoCategory struct {
	TodoID     uuid.UUID
	CategoryID uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
	Role     string
}
