CREATE TABLE TODOS (
    ID UUID PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE CATEGORIES (
    ID UUID PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE TODO_CATEGORY (
    TODO_ID UUID,
    CATEGORY_ID UUID,
    PRIMARY KEY (TODO_ID, CATEGORY_ID)
);

CREATE TABLE USERS (
    ID UUID PRIMARY KEY,
    USERNAME TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    ROLE TEXT NOT NULL DEFAULT 'USER',
    CONSTRAINT CHECK_ROLE CHECK ( ROLE IN ('USER', 'ADMIN') )
);